name: Update Gist

on:
  push:
    branches:
      - main

jobs:
  update-gist:
    environment: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read gist
        id: gist_content
        uses: gorgbus/gist-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_SECRET }}
          GIST_ID: ${{ vars.GIST_ID }}
          GIST_FILENAME: ${{ vars.GIST_FILENAME }}
        with:
          action: "get"
          gist_id: ${{ env.GIST_ID }}
          file_name: ${{ env.GIST_FILENAME }}

      - name: Change content
        id: new_gist
        uses: gorgbus/edit-json-string@main
        with:
          json_string: ${{ steps.gist_content.outputs.content }}
          field: "version"
          value: "1.1.1"

      - name: Update gist
        uses: gorgbus/gist-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_SECRET }}
          GIST_ID: ${{ vars.GIST_ID }}
          GIST_FILENAME: ${{ vars.GIST_FILENAME }}
        with:
          action: "update"
          gist_id: ${{ env.GIST_ID }}
          file_name: ${{ env.GIST_FILENAME }}
          content: ${{ steps.new_gist.outputs.content }}
