name: Build and Publish Tauri App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          
      - name: Install Rust
        run: |
          rustup install stable
          rustup default stable

      - name: Install Sveltekit
        run: |
          npm install -g @sveltejs/adapter-static

      - name: Install Tauri CLI
        run: |
          npm install -g @tauri-apps/cli
          npm install -g @tauri-apps/api

      - name: Install project dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tauri-app
          path: src-tauri/target/release/bundle/

  publish:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: tauri-app
          path: ./release

      - name: Commit and push artifact
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b release-artifact
          mkdir -p artifacts
          mv ./release/* artifacts/
          git add artifacts/
          git commit -m "Auto: Add build artifact"
          git push origin release-artifact --force

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'release-${{ github.sha }}'
          release_name: 'Release ${{ github.sha }}'
          draft: false
          prerelease: false
          files: ./artifacts/*
