name: Update Gist

on:
  push:
    branches:
      - main

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Gist
        env:
          GIST_ID: fbccc6afca03e7ab1c0f7548c79179a5
          GIST_TOKEN: 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
        run: |
          curl -X PATCH \
            -H "Authorization: token $GIST_TOKEN" \
            -d @- \
            https://api.github.com/gists/$GIST_ID
            -d '{
              "files": {
                "version.json": {
                  "content": "{
                    "version": "v0.5.1",
                    "notes": "Test version",
                    "pub_date": "2024-06-20T08:10:26.882Z",
                    "platforms": {
                      "darwin-aarch64": {
                        "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVTY2RUYi9heWVSWEFuVzhYQnZEME0yT3pTcG9GK1ZNZnc5Y0RIYmhLMndXblhRNlg0bVNIMStkbFA3SmhWejYwRkJSTDdvL0JKM2lMTWw0UHNBOE5sTFBYT3NWL1hlRkEwPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzE4ODcxMDIyCWZpbGU6bWVkeC1tZWRpY2FsX3JlY29yZHMuYXBwLnRhci5zego0bStjMzFwSlJrK2ZiTmNjc2xuM3Npc2x6U1BDNTJoNWNlUFZxYlVnVU4rZXZqK0hrQyszL3MxZVAybDk0eWVJVG9mMjdEcWEwOG1MSlRqU0xUSXlBdz09Cg==",
                        "url": "https://github.com/sebascode/2024_Medx_MedicalRecords/releases/latest/download/medx-medical_records_aarch64.app.tar.gz"
                      }
                    }
                  }"
                }
              }
            }'
